title       = "gapminder"
baseURL     = "https://gapminder-cli.tamnd.com/"
description = "A command line for gapminder."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/gapminder-cli"
